function [beta, sigma]=getVarValues(a,b,s,PI) 

alpha = [ones(length([PI.H.CellParams(:).OmegaIndex]),1)*a(1);...
    ones(length([PI.H.IndividualParams(:).OmegaIndex]),1)*a(2);...
    ones(length(setdiff(PI.H.SigmaParams, [PI.H.CellParams(:).OmegaIndex ...
    PI.H.IndividualParams(:).OmegaIndex])),1)*a(3)];

beta = [ones(length([PI.H.CellParams(:).OmegaIndex]),1)*b(1);...
    ones(length([PI.H.IndividualParams(:).OmegaIndex]),1)*b(2);...
    ones(length(setdiff(PI.H.SigmaParams, [PI.H.CellParams(:).OmegaIndex ...
    PI.H.IndividualParams(:).OmegaIndex])),1)*b(3)];

sigma= [ ones(length(PI.H.PopulationParams), 1)*s(1);...
    ones(length([PI.H.CellParams(:).Index]),1)*s(2);
     ones(length([PI.H.IndividualParams(:).Index]),1)*s(3);...
    alpha];
return